name: Cypress Actions
run-name: ${{ github.actor }} Cypress Test Pipeline
on: workflow_dispatch
jobs:
  cypress-test-run:
    runs-on: windows-latest
    env:
      CLOUD_KEY: ${{ secrets.CLOUD_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6  
        with:
          browser: chrome
          runTests: false
      - run: npx cypress run --record --key $CLOUD_KEY

