name: Cypress Actions
run-name: ${{ github.actor }} Cypress Test Pipeline
on: workflow_dispatch
jobs:
  cypress-test-run:
    runs-on: windows-latest
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: node-install  
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cypress run
        uses: cypress-io/github-action@v6  
        with:
          browser: chrome
          runTests: false
          parallel: true
      - run: npm run test:dashboard

